In [1]:
import numpy as np

data = np.array([1, 2, 3], dtype = complex)
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [2]:
data.real

array([1., 2., 3.])

In [4]:
data.imag

array([0., 0., 0.])

In [5]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.empty(3, dtype = np.float64)

array([0., 0., 0.])

In [21]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [22]:
f = lambda m, n: n + 10 * m
A = np.fromfunction(f, (6, 6))
A

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [10., 11., 12., 13., 14., 15.],
       [20., 21., 22., 23., 24., 25.],
       [30., 31., 32., 33., 34., 35.],
       [40., 41., 42., 43., 44., 45.],
       [50., 51., 52., 53., 54., 55.]])

In [24]:
A[-1, :]

array([50., 51., 52., 53., 54., 55.])

In [3]:
import numpy as np
f = lambda m, n: n + 10 * m
A = np.fromfunction(f, (6, 6), dtype=int)
B = A[1:5, 1:5]
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])